title: Just the Learnings
description: This is my real life DevOps documentation
theme: just-the-docs

url: https://pramodvnaik.github.io/learnings

aux_links:
  Template Repository: https://pramodvnaik.github.io/learnings/
